### ISSUE TITLE
Deployment Target

### ISSUE THREAD

**Issue by Sky** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#155]
Hi,
why Branch.framework library deployment target is set to iOS 8.3?
In podspec file platform is set to support iOS 6+ ...

object file (Branch.framework/Branch(Branch.o)) was built for newer iOS version (8.3) than being linked (7.0)

**Comment by shortstuffsushi** [comment]
Whoops, this was just a bad target creation that we missed. This is fixed in 0f56fc3, and uploaded to S3 as of now!
