### ISSUE TITLE
Wrong string length used when converting JSON dict to NSData

### ISSUE THREAD

**Issue by allenhsu** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#157]
https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/blob/master/Branch-SDK/Branch-SDK/BNCEncodingUtils.m#L200

In method `+ (NSData *)encodeDictionaryToJsonData:(NSDictionary *)dictionary`, you used `jsonString.length` instead of length of bytes. As a result, if the dictionary contains non-ascii characters, e.g. Asian characters (which happens mostly in `carrier` field), `jsonString.length` < length of bytes, so the result `NSData` is shorter than jsonString, which result in server returning:
```
Status: 400; Data: {
    error =     {
        code = 400;
        message = "Invalid JSON";
    };
}
```

Solution is quite strait forward:
```
+ (NSData *)encodeDictionaryToJsonData:(NSDictionary *)dictionary {
    NSString *jsonString = [BNCEncodingUtils encodeDictionaryToJsonString:dictionary];
    NSUInteger length = [jsonString lengthOfBytesUsingEncoding:NSUTF8StringEncoding];
    return [NSData dataWithBytes:[jsonString UTF8String] length:length];
}
```

Another solution is use system class `NSJSONSerialization` instead of custom converter:
```
[NSJSONSerialization dataWithJSONObject:dictionary options:0 error:&error];
```

**Comment by allenhsu** [comment]
I believe `strlen([jsonString UTF8String])` works as well.

**Comment by shortstuffsushi** [comment]
Thanks for noticing and fixing this! Much appreciated, catching cases we've missed :+1:
