### ISSUE TITLE
0.11.0 release has min requirement of ios 9

### ISSUE THREAD

**Issue by nosrak113** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#172]
I understand that the 0.11.0 release will have ios dependent features. But many apps will at least  have support for ios 8.X for a couple of months. So would it be possible to lower the min os to 8.X for this release?

**Comment by aaustin** [comment]
Definitely - we just wanted to make sure people who were still on Xcode6 wouldn't get a ton of build errors. It's a good point though - I'll make sure we support it.

**Comment by nosrak113** [comment]
👍 thanks!

**Comment by derrickstaten** [comment]
@nosrak113 this has now been updated. Sorry again. Please let us know ASAP if you run into any issues. Thanks for letting us know.
