### ISSUE TITLE
ld: framework not found CoreSpotlight

### ISSUE THREAD

**Issue by lucianocn** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#178]
Please mark CoreSpotlight framework as OPTIONAL, otherwise it will crash on iOS < 9.

**Comment by lucianocn** [comment]
#173

**Comment by razorberry** [comment]
0.11.3 does not fix this issue

**Comment by aaustin** [comment]
We'll push a fix this morning. I apologize!

**Comment by apersaud** [comment]
+1

**Comment by derrickstaten** [comment]
@lucianocn @razorberry @apersaud please post screenshots of the errors you're seeing. We've been investigating and there are multiple potential issues. 

Also, please post the
1. Base SDK
2. Deployment target

**Comment by derrickstaten** [comment]
Also, if you set Base SDK to iOS 9, does this resolve the issue?

**Comment by apersaud** [comment]
iOS 8.4 SDK, target iPhone 8.0. Basically you are trying to link CoreSpotlight which is only available on latest XCode with iOS9. Some of us are still on XCode 6.4 with iOS 8.4 SDK (Swift 1.2).

**Comment by derrickstaten** [comment]
We only try to link it optionally, as far as I can tell. However, there are other errors when it's optionally linked and it still includes CoreSpotlight methods. Can you please post the error message @apersaud. Then I can know whether the optional linking is the issue or if it's one step further removed.

**Comment by apersaud** [comment]
iOS9 SDK is only available on XCode 7+ which also requires migrating to Swift 2.0 from 1.2. If you take an example Branchapp (with the 11.3 SDK) and compile it with XCode 6.4 you will see the link error.
![screen shot 2015-09-16 at 12 22 21 pm](https://cloud.githubusercontent.com/assets/127068/9915745/9b15f7ce-5c6d-11e5-8721-fb3f9d424475.png)

**Comment by derrickstaten** [comment]
@apersaud would you be open to Skyping? My handle is dstaten

**Comment by derrickstaten** [comment]
If not, can you tell us whether you're using the Cocoapod or the .framework file? And are you on Xcode 6.4 or Xcode 7.x?

**Comment by apersaud** [comment]
I'm using Cocoapods as a normal static library approach (not using frameworks). XCode 6.4. Sure, we can also do http://appear.in or Skype @modernistik.

**Comment by derrickstaten** [comment]
Okay thanks. We're working on making both the Cocoapods and the .framework file usable on older builds. Really sorry for the headache.

**Comment by razorberry** [comment]
using cocoapods

http://cl.ly/image/282903010f0s

Screenshot of pod project with CoreSpotlight set as required, 0.11.3

**Comment by jbelkins** [comment]
+1 on this.  We are trying to do one last release on Xcode 6.4.1 / iOS 8 SDK today and would like to get this update in.  We get the same linker error.  Our deployment target is 7.0

**Comment by derrickstaten** [comment]
you can also revert to using an old version of the SDK for today, `pod 'Branch', '0.10.9'` and run `pod update`. We're close but haven't finished fixing all issues yet.

**Comment by derrickstaten** [comment]
@jbelkins @razorberry @apersaud we released a new version. Please note that you should not strongly link CoreSpotlight. Either weakly link or leave it out completely.

0.11.4

**Comment by lucianocn** [comment]
#180

**Comment by Ecarrion** [comment]
Builds in Circle CI using `0.11.4` using `xCode 6.4`
```
machine:
  xcode:
    version: "6.4"
```
Are failing with the same error `framework not found CoreSpotlight`

**Comment by derrickstaten** [comment]
@Ecarrion we removed even weak references to CoreSpotlight in the Branch podspec for the soon to be released `0.11.5`. You can see that on this PR: https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/pull/185
