### ISSUE TITLE
How to get parameters when the app is in background 

### ISSUE THREAD

**Issue by suhitp** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#184]
When the app is in background we call
```
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication
         annotation:(id)annotation
{
    if (![[Branch getInstance] handleDeepLink:url]) {
    // do other deep link routing for the Facebook SDK, Pinterest SDK, etc
   } else {
    //handle the link
  }
   return YES;
}
```
how do I get the url parameters from the link 'myapp://open?link_click_id=12345'. set in my dashboard to navigate to the deep link screen.

**Comment by aaustin** [comment]
@suhitp sorry for the delay! When `myapp://open?link_click_id=12345` is triggered, Branch will return the dictionary full of deep link data in the deep link handler block that you registered in the `initSession` call in `didFinishLaunchingWithOptions`.

I hope this helps!

**Comment by suhitp** [comment]
@aaustin  thanks for the response, any quick way to get the parameters inside when we tap on link

- (BOOL)application:application openURL: sourceApplication: annotation:
   
  when the app comes to foreground from background by branch deeplink click, it takes lot of time to get the url and route to the exact place.

**Comment by aaustin** [comment]
When you create the link, you can customize the deeplink path by specifying '$deeplink_path' : 'special/deep/link', and we'll create the URI: `myapp://special/deep/link?link_click_id=12345`

Our servers are extremely fast. It should take less than 100 ms round trip for an init call. You just want it to be instantaneous? Make sure you use routing from fresh install from our handler at least!
