### ISSUE TITLE
Warnings when generating dSYM with 0.11.4

### ISSUE THREAD

**Issue by zac** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#191]
#### Description
I'm getting several hundred warnings on the "GenerateDSYMFile" step of the build process with warnings such as:

```
while processing /Users/zac/MyProject/Vendor/Branch.framework/Branch(BNCServerRequest.o):
warning: /var/folders/vw/btz_bylj5vx_7vpzw74lvkbw0000gn/C/org.llvm.clang.derrickstaten/ModuleCache/V72NIT1MFFNB/Foundation-K7W1BMS6PHG4.pcm: No such file or directory
while processing /Users/zac/MyProject/Vendor/Branch.framework/Branch(BNCServerRequest.o):
warning: Could not resolve external type c:objc(cs)NSObject
```

Please notice the hard-coded clang module cache path.

#### Steps to Reproduce:

1. Create a new blank project.
2. Edit the "Debug Information Format" build configuration to produce "DWARF with dSYM File" when building with the Debug configuration (or just compile with Release).
3. Integrate the Branch.framework using [the Quickstart Guide](https://dev.branch.io/recipes/quickstart_guide/).
4. Build the project.

**Expected:** The project should build with no issues.
**Actual:** The project produces multiple build warnings relating to the generation of the dSYM.

**Comment by zac** [comment]
Still an issues with the 0.11.5.

**Comment by JackoPlane** [comment]
+1

**Comment by derrickstaten** [comment]
@zac can you verify that the issues are no longer present if you use the framework on this branch: https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/tree/test-build

**Comment by Sarkar** [comment]
@zac @JackoPlane hey guys, super sorry about this. Thanks for the super clear update - @derrickstaten and I found a workaround to this thanks to your help, and tested this new framework on clean projects on a few machines - no more errors!

Before we update our framework to S3, we'd love for you to try; no code / other updates introduced from `0.11.6`, but the warnings should be gone now. Should be as simple as replacing your .framework and re-cleaning & building. Can you guys confirm?

https://s3-us-west-1.amazonaws.com/branchhost/Branch-iOS-SDK-Temp.zip

**Comment by zac** [comment]
@Sarkar Hm, I'm getting similar errors but with `org.llvm.clang.sahilverma` hard-coded in the ModuleCache path:

```
while processing /Users/zac/MyProject/Vendor/Branch.framework/Branch(BNCServerRequest.o):
warning: /var/folders/9w/_7jwckd95f74ttzldx7g2m2m0000gn/C/org.llvm.clang.sahilverma/ModuleCache/2UWIH76MED9PA/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
while processing /Users/zac/MyProject/Vendor/Branch.framework/Branch(BNCServerRequest.o):
warning: /var/folders/9w/_7jwckd95f74ttzldx7g2m2m0000gn/C/org.llvm.clang.sahilverma/ModuleCache/2UWIH76MED9PA/Foundation-3DFYNEBRQSXST.pcm: No object file for requested architecture
```

**Comment by zac** [comment]
@JackoPlane Did the above build work for you?

**Comment by JackoPlane** [comment]
Nope.

**Comment by Sarkar** [comment]
@zac and @JackoPlane not to sound like a broken record, but I think we've fixed it for sure this time. It seems like this problem creeped up with XCode 7 Beta 5 and stuck in the GM. There were several recommendations on the Apple Forums, and after careful evaluation we did the necessary ones and tested again. It looks like they're gone for good. One last time, could you try it out? Thanks so much for your help, guys.

https://s3-us-west-1.amazonaws.com/branchhost/Branch-iOS-SDK-Temp.zip

**Comment by zac** [comment]
@Sarkar Works for me, thanks!

:tada: :dancer: :tada: 

<img width="238" alt="no-issues" src="https://cloud.githubusercontent.com/assets/2525/10498066/61384eb8-727e-11e5-8634-01a2a93954b1.png">

**Comment by Sarkar** [comment]
Awesome! I'll leave this open until we get the changes merged into master. Thanks again
