### ISSUE TITLE
Test failed in iOS9

### ISSUE THREAD

**Issue by Hibbert-pku** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#193]
Hi,
    iOS version of branchIO in circleCI is iOS8,so when I use xcode7&iOS9 to run the test, the BNCServerInterfaceTests was failed. After I delete the iOS9 code in BNCServerInterface.m between line 77 and 128, the tests were passed.

**Comment by Sarkar** [comment]
Hibbert,

Thanks for telling us about this. We're certainly aware of this ourselves, and we're going to update tests very shortly. Please hang tight!

cc @aaustin @derrickstaten

**Comment by derrickstaten** [comment]
Tests are passing on master again. Resolving.
