### ISSUE TITLE
I don't think this library supports Gmail share subject lines?

### ISSUE THREAD

**Issue by jbkielis** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#197]
Is that accurate?  If not, any chance you are going to add that support?  Thanks.

**Comment by derrickstaten** [comment]
Presumably you're referring to the BranchActivityItemProvider, a subclass of UIActivityItemProvider. Unfortunately in our experience that's a limitation of sharing via UIActivityViewController -> Gmail. If you have sample code or a library that supports this, we'd be happy to look into it.

**Comment by francisjervis** [comment]
Have you tried the following:
https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UIActivityItemSource_protocol/index.html#//apple_ref/occ/intfm/UIActivityItemSource/activityViewController:subjectForActivityType: <https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UIActivityItemSource_protocol/index.html#//apple_ref/occ/intfm/UIActivityItemSource/activityViewController:subjectForActivityType:>

**Comment by nehasharma1101** [comment]
I am also facing the problem with Gmail. The subject & body is taking same value as of body..
Is there any solution for this error.. I did R&D but didn't find anything.

**Comment by hemangshah** [comment]
https://stackoverflow.com/questions/34264751/uiactivityviewcontroller-gmail-share-subject-and-body-going-same

It's still same in 2018. 🔥

**Comment by E-B-Smith** [comment]
Yeah - go file a bug with gmail about it!

If enough people file one maybe they’ll fix it.

**Comment by hemangshah** [comment]
Submitted – https://productforums.google.com/forum/#!topic/gmail/9JRqN0rVxYo;context-place=forum/gmail
