### ISSUE TITLE
initSessionWithLaunchOptions called multiple times

### ISSUE THREAD

**Issue by Ankish** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#210]
Branch *branch = [Branch getInstance];
    [branch initSessionWithLaunchOptions:launchOptions andRegisterDeepLinkHandler:^(NSDictionary *params, NSError *error){

    }

 initSessionWithLaunchOptions:launchOptions is called multiple times 
.Whenever A Permission is granted .OS calls didBecomeActive which inturn calls your initSessionWithLaunchOptions:launchOptions .

**Comment by derrickstaten** [comment]
@Ankish thanks for noting this. This will require a fairly substantial restructuring of our SDK. Anytime we change functionality around initSession, we have to do a lot of manual testing to make sure we don't break anything for existing partners. 

For now, you can store the data from the first initSession (before you ask the user for permissions) in NSUserDefaults or another ephemeral store, then retrieve this data after you've finished asking for permissions. You can also delay asking the user for permissions until later in the onboarding process, a technique I successfully used at my last company to get a higher number of users to agree to push notifications, etc.
