### ISSUE TITLE
BNCServerRequests.h not found from BNCServerRequestQueue.h

### ISSUE THREAD

**Issue by helloandrewpark** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#215]
This is for 0.11.8 via Cocoapods

I wasn't able to see it in master also

**Comment by derrickstaten** [comment]
@helloandrewpark can you delete your Pods directory, as well as the Podfile.lock, then reinstall the pods by running `pod install`? We currently are unable to reproduce locally.

Also, we're happy to examine a test project with this, please zip it up and send to support@branchmetrics.io

**Comment by derrickstaten** [comment]
@helloandrewpark we've been unable to reproduce. Please let us know if this continues to be an issue after you follow the steps above.
