### ISSUE TITLE
Crash on iOS 7.0.1 (NSUserActivity)

### ISSUE THREAD

**Issue by jberlana** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#240]
Hello guys, I am having problems on iOS 7.

Is because of the use of NSUserActivity and Handoff options that appeared on iOS8.
```
dyld: Symbol not found: _NSUserActivityTypeBrowsingWeb
  Referenced from: /var/mobile/Applications/7A3B4B99-5822-419B-BE10-416A53A790AB/Comprea.app/Comprea
  Expected in: /System/Library/Frameworks/Foundation.framework/Foundation
 in /var/mobile/Applications/7A3B4B99-5822-419B-BE10-416A53A790AB/Comprea.app/Comprea
```

How can I solve the crash? are you still supporting iOS7?
Thanks.

**Comment by derrickstaten** [comment]
Based on our conversation via email it seems like you're unable to reproduce on the latest SDK. Please reopen if this crash reappears.
