### ISSUE TITLE
Is there a reason enableCookieBasedMatching is off by default?

### ISSUE THREAD

**Issue by DimaVartanian** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#241]
After reading this post https://blog.branch.io/install-attribution-ios-9-safari-view-controller it seems like the safari cookies are a big step forward so I'm wondering why it seems to be off by default? I have not turned it on yet for this reason (not knowing if there are some unknown negatives). Thanks!

**Comment by derrickstaten** [comment]
@DimaVartanian we're working on squashing some bugs here still. We'll let you know when this is fixed.

**Comment by DimaVartanian** [comment]
Hi Derrick! Thanks. I'll keep an eye on this ticket in the meantime and leave the option off until you say so.

**Comment by derrickstaten** [comment]
@DimaVartanian can you try this branch out: https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/tree/100-matching-prototype? This has worked in my testing.

To ensure it's making use of the SFSafariViewController, please:
1. in your code, turn off `setDebug` and turn on `enableCookieBasedMatching`
2. on your test device, delete the app (and all other apps with this URI scheme :) )
3. on your test device, turn on wifi
4. on your test device, clear browser cookies (Settings > Safari > Clear History and Website Data)
5. click a link
6. turn off wifi. this forces an IP address changing, which breaks all existing matching mechanisms
7. install the app from Xcode. if params are present, it worked. If not we can debug what may need to change with the setup.

Be sure this in no way impacts your view hierarchy. We create a second UIWindow with `alpha:0` and set its property `hidden` to `NO`. This shouldn't impact anything -- and we want to make sure it doesn't.

**Comment by derrickstaten** [comment]
@kubbing can you take a look at this as well? I'd love to see if this resolves the issues you previously experienced with the status bar and view hierarchy. Our approach now is to never make our second window the key window, and we don't make CGRect zero but rather the same as the main window's bounds.

**Comment by derrickstaten** [comment]
This fix has now been merged into master and will be in the 0.11.12 release momentarily

**Comment by danwalkowski** [comment]
it appears to work for me too!
