### ISSUE TITLE
Show share sheet completion handler

### ISSUE THREAD

**Issue by josh-fuggle** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#242]
Hello,

Is it possible to add a share sheet completion handler to the `BranchUniversalObject` class?

See API:

https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/blob/master/Branch-SDK/Branch-SDK/BranchUniversalObject.h#L42

`UIActivityViewController` has a `completionHandler` property.

I want to find out when the user has finished sharing so that I can update the UI.

Ta

Josh

**Comment by derrickstaten** [comment]
@josh-fuggle I believe the current completion handler fires when the sheet is successfully presented. Feel free to open a pull request if you think this should have additional functionality (i.e. a callback when the share is complete)! Let us know if you have questions.

**Comment by aaustin** [comment]
@josh-fuggle Let us know if you think we must add more to this share sheet. https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/blob/master/Branch-SDK/Branch-SDK/BranchUniversalObject.h#L43 Closing the issue for now!

**Comment by josh-fuggle** [comment]
Hi @aaustin, just getting back to this issue now. I was about to fork and start a new PR, but then noticed that someone already has a PR to fix this issue! Will wait until it has been merged in then.

https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/pull/270
