### ISSUE TITLE
continueWithUserActivity use 

### ISSUE THREAD

**Issue by pgherveou** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#254]
Not sure what this method is supposed to do exactly but its hard coded to use bnc.lt and will always return false in our app since we use white labeled domain

https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/blob/6a168d352ce6b8b41b30e19f684b40730ccd0904/Branch-SDK/Branch-SDK/Branch.m#L392

**Comment by derrickstaten** [comment]
@pgherveou we are planning on adding the ability for users to specify additional Universal Link domains so that this can return `YES`. In the meantime, even though we return `NO`, we still send that link back to our server and will appropriately retrieve data / deeplink.

**Comment by derrickstaten** [comment]
@pgherveou feel free to test out https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/pull/255

**Comment by derrickstaten** [comment]
This fix has now been merged into master and will be in the 0.11.12 release momentarily

**Comment by serluca** [comment]
@derrickstaten can you update the documentation with this feature?

**Comment by derrickstaten** [comment]
@serluca you're right, we'll need to find a way to document this. In the meantime, see this comment on the PR: https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/pull/255#issue-121623125

**Comment by urbanappetite** [comment]
Bump on the docs - so glad I could look through the source to figure out the issue we were having
