### ISSUE TITLE
-[BranchUniversalObject showShareSheetWithShareText] callback misunderstanding

### ISSUE THREAD

**Issue by garnett** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#267]
```showShareSheetWithShareText``` is really useful method because it simplifies presenting of branch universal object, however I doubt if ```callback``` in it's current implementation is useful. Nobody is really concerned in event where share sheet is presented: what I am interested in when sharing content is to actually catch the moment when content was shared (or failed).

This is why I propose to change callback type to ```UIActivityViewControllerCompletionWithItemsHandler```. I have to admit it is pretty leaky API, but benefits of changling callback type still might outweigh other options such as **copy-pasting ```showShareSheetWithShareText``` code from SDK** and maintaining more configurable version inside of app itself.

Will be happy to do PR if the change seems feasible.

**Comment by aaustin** [comment]
@garnett This seems like it would be useful. If you want to add in a new showShare sheet method with this callback exposed, we'd definitely give it a review. Thanks for your contribution!

**Comment by francisjervis** [comment]
This would indeed be useful (if I understand your suggestion correctly). I was using this as below and depend on activity to log content shares to analytics and error to, well, log errors...

    shareViewController.completionWithItemsHandler = {(activity, success: Bool, items, error)

**Comment by garnett** [comment]
As @francisjervis correctly pointed, main point of callback in sharing method is to check for error / log analytics events.

I decided to implement new methods for exposing this callback and deprecate old methods (with wrong callback triggering). It is possible to adjust old methods as well to call ```callback``` when sharing is actually finished, but I do not really see point for this because this callback won't tell if sharing was successful or failed.

https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/pull/270

**Comment by derrickstaten** [comment]
Thanks @garnett!
