### ISSUE TITLE
Deep link handler never called when initializing session with user activity

### ISSUE THREAD

**Issue by SamClewlow** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#277]
### Test Conditions 
- iOS 9.2
- iPhone 6s Plus
- Branch Test Key
- SDK v0.11.14

### Scenario
The app is launched from a cold start via a deep link. The `launchOptions` passed to 
```objective-c 
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
``` 
contain an  `NSUserActivity`, shown below:

```objective-c
    {
        UIApplicationLaunchOptionsUserActivityDictionaryKey =     {
            UIApplicationLaunchOptionsUserActivityIdentifierKey = "EFC7D9B0-079E-4D04-95BD-E4A66B7C4F8C";
            UIApplicationLaunchOptionsUserActivityKey = "<NSUserActivity: 0x14fd760a0>";
            UIApplicationLaunchOptionsUserActivityTypeKey = NSUserActivityTypeBrowsingWeb;
        };
    }
```
   

When calling 

```objective-c
- (void)initSessionWithLaunchOptions:(NSDictionary *)options andRegisterDeepLinkHandler:(callbackWithParams)callback;
```

and passing launch options that contain the user activity, the `callbackWithParams` block is never called. Looking at the Branch code, session initialization gets as far as the following method, then drops through as it does not meet any of the conditions. 

```objective-c
- (void)initSessionWithLaunchOptions:(NSDictionary *)options isReferrable:(BOOL)isReferrable explicitlyRequestedReferrable:(BOOL)explicitlyRequestedReferrable automaticallyDisplayController:(BOOL)automaticallyDisplayController {
    self.shouldAutomaticallyDeepLink = automaticallyDisplayController;
    
    self.preferenceHelper.isReferrable = isReferrable;
    self.preferenceHelper.explicitlyRequestedReferrable = explicitlyRequestedReferrable;

    // Handle push notification on app launch
    if ([options objectForKey:UIApplicationLaunchOptionsRemoteNotificationKey]) {
        id branchUrlFromPush = [options objectForKey:UIApplicationLaunchOptionsRemoteNotificationKey][BRANCH_PUSH_NOTIFICATION_PAYLOAD_KEY];
        if ([branchUrlFromPush isKindOfClass:[NSString class]]) {
            self.preferenceHelper.universalLinkUrl = branchUrlFromPush;
        }
    }
    
    if ([BNCSystemObserver getOSVersion].integerValue >= 8) {
        if (![options objectForKey:UIApplicationLaunchOptionsURLKey] && ![options objectForKey:UIApplicationLaunchOptionsUserActivityDictionaryKey]) {
            [self initUserSessionAndCallCallback:YES];
        }
        else if ([options objectForKey:UIApplicationLaunchOptionsUserActivityDictionaryKey]) {
            self.preferenceHelper.isContinuingUserActivity = YES;
            if (self.accountForFacebookSDK) {
                id activity = [[options objectForKey:UIApplicationLaunchOptionsUserActivityDictionaryKey] objectForKey:@"UIApplicationLaunchOptionsUserActivityKey"];
                if (activity && [activity isKindOfClass:[NSUserActivity class]]) {
                    [self continueUserActivity:activity];
                }
            }
        }
    }
    else if (![options objectForKey:UIApplicationLaunchOptionsURLKey]) {
        [self initUserSessionAndCallCallback:YES];
    }
}
```

**Comment by aaustin** [comment]
@SamClewlow Do you have the code in your continueUserActivity and handleDeepLink? Init session depends on those methods being called when there are launch options like that. Here's the docs:
1. https://dev.branch.io/recipes/add_the_sdk/ios/#handle-deep-link
2. https://dev.branch.io/recipes/add_the_sdk/ios/#continue-user-activity

**Comment by SamClewlow** [comment]
@aaustin Hi Alex,

Thanks for coming back so quickly, I find that when launching from a cold start with a deep link 

```objective-c
- (BOOL)application:(UIApplication *)application
continueUserActivity:(NSUserActivity *)userActivity
 restorationHandler:(void (^)(NSArray *restorableObjects))restorationHandler
```

is never called.

**Comment by aaustin** [comment]
It seems a new issue just now reporting the same thing. With our testbed app (in this repo https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/blob/master/Branch-TestBed/Branch-TestBed/AppDelegate.m), I'm unable to reproduce. If you're looking at the logs, you have to use the device manager instead of the Xcode terminal since it won't connect to Xcode with an externally triggered app launch.

Can you send over your app delegate code? If you don't want to post it publicly, can you start a convo with our support team at support@branch.io. Sorry about the hassle!

**Comment by SamClewlow** [comment]
Thanks @aaustin 

I've looked into this more, and resolved the issue.

```objective-c
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
```

was returning `NO` (sigh), so 

```objective-c
- (BOOL)application:(UIApplication *)application
continueUserActivity:(NSUserActivity *)userActivity
 restorationHandler:(void (^)(NSArray *restorableObjects))restorationHandler
```

was never called.

The issue in my case was directly returning the result of the Facebook SDK call 

```objective-c
[[FBSDKApplicationDelegate sharedInstance] application:application
                                        didFinishLaunchingWithOptions:launchOptions];
```

which returns NO as the deep link is not a Facebook one.

I really appreciate your help, and hope this answer might help others experiencing similar issues!

Cheers
Sam

**Comment by turok** [comment]
Have the same issue, Thanks, @SamClewlow!

**Comment by derrickstaten** [comment]
@turok 

Do you by any chance use the Facebook SDK? If so, do you let it handle the return statement in `application:didFinishLaunchingWithOptions:`?

If so, Facebook will sometimes return NO at the end of that method when a Universal Link is clicked. When it does this, it causes `application:continueUserActivity:restorationHandler:` to *not* be invoked, and then Branch fails to initialize. 

If you do use the Facebook SDK in this way, please try instead changing `application:didFinishLaunchingWithOptions:` to always return `YES`. This should resolve the issue.

Alternatively, you could upgrade to the latest version of the SDK (0.11.14 or newer), then add this one line of code:

`[branch accountForFacebookSDKPreventingAppLaunch];`

Please let us know if this resolves the issue for you! If not, please email support@branch.io with the following:

1. Can you send over your implementation of `application:didFinishLaunchingWithOptions:`? 

2. Please turn on `setDebug` (https://dev.branch.io/recipes/testing_your_integration/ios/#use-setdebug-to-simulate-fresh-installs) and send us the logs, as well as the link you're clicking. Also, be sure that you have the Branch SDK code in `application:continueUserActivity:restorationHandler:` (code here: https://dev.branch.io/recipes/add_the_sdk/ios/#continue-user-activity). Please also send over your code for `application:openURL:sourceApplication:annotation:` and `application:continueUserActivity:restorationHandler:` (minus any sensitive keys/code).

**Comment by hammadjamal** [comment]
Hi,
I am having issue with this same thing.
I am also doing this in my `application:didFinishLaunchingWithOptions:` method.
```
return [[FBSDKApplicationDelegate sharedInstance] application:application
                                       ` `didFinishLaunchingWithOptions:launchOptions];
```
but as said earlier before initializing my branch session that is 
```
branchInstance.initSessionWithLaunchOptions(launchOptions, andRegisterDeepLinkHandler: { params, error in
            if (error == nil) {
                   NSLog("params: %@", params.description)
             }
        })
```
I have added 
```
branchInstance.accountForFacebookSDKPreventingAppLaunch()
```
But still my registerDeepLinkHandler is not working and I am not recieving any parameters.
But if I Return YES instead of 
```
return [[FBSDKApplicationDelegate sharedInstance] application:application
                                        didFinishLaunchingWithOptions:launchOptions];
```
in `application:didFinishLaunchingWithOptions:` method its works perfectly.
Could you guys help me with this issue.
My Branch SDK version is **0.11.16**.

**Comment by derrickstaten** [comment]
@hammadjamal that's odd, as `accountForFacebookSDKPreventingAppLaunch` should properly handle this. Could you send over your code for `application:didFinishLaunchingWithOptions:` and `application:continueUserActivity:restorationHandler:` to support@branch.io? Then we can take a look. If you have a sample project, all the better.

**Comment by andrespch** [comment]
Hi, I 'm experiencing the same issue, 
`branchInstance.accountForFacebookSDKPreventingAppLaunch()`
is not working as supposed.

**Comment by TheChuckster** [comment]
Does anyone have a strong consensus/definitive on what the correct didFinishLaunchingWithOptions implementation should look like when mixing and matching Branch+FB SDK login? 

Right now, I am calling Branch instance's selector accountForFacebookSDKPreventingAppLaunch, throwing out the return value of the FBSDKApplicationDelegate didFinishLaunchingWithOptions selector, initializing my Branch session (while registering a deep link handler), and then I'm always returning YES at the very end.

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    [[Branch getInstance] accountForFacebookSDKPreventingAppLaunch];

    [[FBSDKApplicationDelegate sharedInstance] application:application didFinishLaunchingWithOptions:launchOptions];

    [[Branch getInstance] initSessionWithLaunchOptions:launchOptions andRegisterDeepLinkHandler:^(NSDictionary *params, NSError *error) {
        RLOGI(@"deep link data: %@", [params description]);
    }];
    
    return YES;
}
```

The documentation is a little unclear on how to do this.

**Comment by derrickstaten** [comment]
Hi @TheChuckster. Sorry for the confusion. You should choose one of the following:

1. Always `return YES;`, and do *not* invoke `[[Branch getInstance] accountForFacebookSDKPreventingAppLaunch];`
2. Allow the Facebook SDK to determine whether `application:didFinishLaunchingWithOptions:` returns `YES` or `NO`, and invoke `[[Branch getInstance] accountForFacebookSDKPreventingAppLaunch];`

The reason for this second option is that the Facebook SDK will return `NO` if a Universal Link opens the app but that UL is not a Facebook UL. Some developers did not always want to modify `application:didFinishLaunchingWithOptions:` to always return YES, so we instead provided a way to account for that behavior.

I think you should remove `[[Branch getInstance] accountForFacebookSDKPreventingAppLaunch];`:
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    [[FBSDKApplicationDelegate sharedInstance] application:application didFinishLaunchingWithOptions:launchOptions];

    [[Branch getInstance] initSessionWithLaunchOptions:launchOptions andRegisterDeepLinkHandler:^(NSDictionary *params, NSError *error) {
        NSLog(@"deep link data: %@", [params description]);
    }];

    return YES;
}
```

Let us know if you have questions about this, and sorry again for the confusion.

**Comment by TheChuckster** [comment]
That makes much more sense. As feedback, perhaps the documentation should mention this as well -- you explained it in a much clearer way.

**Comment by derrickstaten** [comment]
@TheChuckster I added this to branch.h, thanks for the feedback!
