### ISSUE TITLE
not can routing user when kill app

### ISSUE THREAD

**Issue by huongtran84** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#279]
If my app is launched it no problem with universal link and deeplink but when I kill app and click on deeplink app launch but it can not route user maybe inIntSession is not callback

**Comment by aaustin** [comment]
Hi @huongtran84 - I just tested this with our testbed. It appears to be working correctly, where continueUserActivity is called from first open. Do you have the code in your continueUserActivity and handleDeepLink? Init session depends on those methods being called when there are launch options like that. Here's the docs:
1. https://dev.branch.io/recipes/add_the_sdk/ios/#handle-deep-link
2. https://dev.branch.io/recipes/add_the_sdk/ios/#continue-user-activity

If you do, can you send over your App Delegate code? You can start a private convo with our support team at support@branch.io if you don't want to share publicly.

**Comment by SamClewlow** [comment]
Hi @huongtran84, have you checked that your app delegate method 

```objective-c
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
```

returns `YES`?

I had a similar issue, which is resolved, see the link here - Issue: https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/issues/277 .
Sam
