### ISSUE TITLE
I want to add two links in the ShareSheetStyle part of branch io one of details of the post and second for the playstore link, how to do this in android ? Please help me as I am working on this since last week.

### ISSUE THREAD

**Issue by shrutika229** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#281]
final LinkProperties linkProperties = new LinkProperties()
                            .setChannel("facebook")
                            .setFeature("sharing")
                            .addControlParameter("id",""+id)
                            .addControlParameter("$desktop_url",share_link)
//                            .addControlParameter("$android_deeplink_path", "Download App -https://play.google.com/store/apps/details?id=com.clinate.clinate&hl=en");
                            .addControlParameter("$android_url1", share_link)
                            .addControlParameter("$android_url2", "Download APP -"+"https://play.google.com/store/apps/details?id=com.clinate.clinate&hl=en");

**Comment by ahmednawar** [comment]
@shrutika229  please submit a ticket via support@branch.io. This is our iOS SDK repo, whereas your question is about Android.
