### ISSUE TITLE
Branch assumes AppDelegate will have a property called window and crashes if not.

### ISSUE THREAD

**Issue by aepryus** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#290]
The following change at line 107 in BNCStrongMatchHelper.m fixes the issue:

`		self.secondWindow = [[UIWindow alloc] initWithFrame:[[[[UIApplication sharedApplication] windows] firstObject] bounds]];
`

**Comment by derrickstaten** [comment]
@aepryus do you have a stack trace of the crash?

Thank you for reporting this! Would you be willing to open a pull request against our repo? Otherwise we can do so.

Thanks again!

**Comment by aepryus** [comment]
Sure, I tried to create a pull request earlier, but it wouldn't let me check in a new branch.  I'm dealing with an unrelated minor emergency at the moment, but after that I'll submit a PR.  Thanks a lot.

**Comment by aepryus** [comment]
I'm having some difficulty pushing my branch up.  It's probably some configuration error on my end, but just in case, do I need any permissions to push a branch to the repository?

I'm still fighting some unrelated fires, but I'll try to get some time tonight to work on this again.

**Comment by derrickstaten** [comment]
You'd have to push up a branch on a forked version of the repo, rather than pushing to the repo directly. Would you prefer we add this in? It should be easy to verify and add on our end.

**Comment by aepryus** [comment]
Thanks for your hint.  Submitted the PR.

**Comment by ahmednawar** [comment]
@aepryus Sorry this took a long time, this was merged in today. We submitted another PR for formatting reasons. Thanks again! Closing here, feel free to reopen if anything comes up
