### ISSUE TITLE
Deprecated completionHandler warning if deployment target is iOS 8 or higher

### ISSUE THREAD

**Issue by staminajim** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#297]
If your deployment target is iOS 8 or higher, Xcode throws a warning for this line:
https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/blob/master/Branch-SDK/Branch-SDK/BranchUniversalObject.m#L162
since it's been deprecated.  I'll throw up a pull request soon - it should just be a matter of suppressing the warning since the new not deprecated completionHandler is handled directly above it.

**Comment by ahmednawar** [comment]
@staminajim thanks for noting that..looking forward to the PR!

**Comment by staminajim** [comment]
@ahmednawar Cheers, just added the pull request.
