### ISSUE TITLE
Links not working when third-party app opens with Safari View Controller

### ISSUE THREAD

**Issue by illonks** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#300]
When I open a branch generated link in a third-party app, if that app opens the link using Safari View Controller, the banner that shows up in Safari to open the app if it exists doesn't show up anymore and the link won't auto-open the app (this is all when the app is installed on the phone). However, using another app where opening the link doesn't open SVC, it works as advertised - the app is opened directly when it exists. How can this be worked around? Thanks!

**Comment by ahmednawar** [comment]
@illonks-- We observed that if you click a Universal Link in an app where it shows a UIWebView or SFSafarViewController, it doesn’t work. It is a limitation by Apple. If the app calls application:OpenURL it will work correctly.

I am not sure though why the smart banner doesn’t show up. Could you please send us steps to reproduce: which app you are using and a link to test with? If you’d rather not share the link or steps to reproduce here, feel free to shoot us a note via suppport@branch.io

Thanks!

**Comment by ahmednawar** [comment]
@illonks Thanks for sending the info. 

I reproduced the bug on my end. Unfortunately both problems lie in Apple's hands. We don't control Universal Links routing or displaying the banner. Hope I could help here :(

Hopefully they fix this in the upcoming releases.
