### ISSUE TITLE
showShareSheetWithLinkProperties triggers deep link behaviour on app resume with some applications

### ISSUE THREAD

**Issue by teodora92** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#301]
iOS version: 9.2.1

Production environment: debug and release

Steps to reproduce:
1. create a BranchUniversalObject
2. call the showShareSheetWithLinkProperties method of the universal object
3. share with the Notes or Reminders iOS applications
4. Press home button
5. Resume application
6. The callback method of the Branch instance is called with the data of the universal object that was previously shared and has the +clicked_branch_link property set to true/1

This behaviour does not appear when sharing to Facebook, WhatsApp, Twitter etc. In these cases a normal callback with no additional data is performed.

**Comment by ahmednawar** [comment]
@teodora92 I answered on #302..closing here
