### ISSUE TITLE
Please give a parameter to mute [Branch Warning] in using test key in test binary.

### ISSUE THREAD

**Issue by zhens** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#309]
It keeps printing the warning, it is a little verbose for release engineer.

**Comment by ahmednawar** [comment]
@zhens Thanks for pointing this out..will be adding this in our next release

**Comment by ahmednawar** [comment]
@zhens We've just pushed a new release with this feature...the method is called suppressWarningLogs on the Branch object.

Cheers!
