### ISSUE TITLE
Crash on iOS 8.1 Simulator when using carthage

### ISSUE THREAD

**Issue by hovox** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#310]
The crash is also happening on device with iOS 8.1 . 

dyld: Symbol not found: ___NSDictionary0__
 Referenced from: /Users/davitpiloyan/Library/Developer/CoreSimulator/Devices/64CD8679-1086-4EF9-AEEA-F885B301259B/data/Containers/Bundle/Application/AB072552-A5C6-4453-8623-94F461A95128/PicsArt.app/Frameworks/BranchSDK.framework/BranchSDK (which was built for iOS 9.2)
 Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 8.1.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
in /Users/davitpiloyan/Library/Developer/CoreSimulator/Devices/64CD8679-1086-4EF9-AEEA-F885B301259B/data/Containers/Bundle/Application/AB072552-A5C6-4453-8623-94F461A95128/PicsArt.app/Frameworks/BranchSDK.framework/BranchSDK

**Comment by hovox** [comment]
I think it maybe because target version for framework is set to 9.2, adding `IPHONEOS_DEPLOYMENT_TARGET='8.0'` into build_framework.sh file may fix the issue

**Comment by ahmednawar** [comment]
@hovox Thanks for reporting this. You are absolutely correct! I've updated the framework now. Could you please update? If you have any problems, please let me know.

Thanks again!

**Comment by hovox** [comment]
@ahmednawar  Seems fixed. Thanks.

I have noticed that there is no carthage xCode project in the BranchMetrics repository, am I right ?
I'm wandering why are you not pushing carthage xCode project in this repo?

**Comment by ahmednawar** [comment]
@hovox Sorry for the late reply. The reason is that I forgot :) You will find the files now under `Carthage` on `master`

I am closing here. Feel free to reopen if you encounter any issues. Thanks again for the feedback!
