### ISSUE TITLE
Callback comes back in the background - never called in the foreground

### ISSUE THREAD

**Issue by arrows** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#316]
Hi,

I noticed that if I launch my app (from the _background_), and then put it very quickly in the background again, the branch callback (initSessionWithLaunchOptions) is being called in the background. 
That's OK, but the problem is that when the app comes back the next time to the foreground - the callback is never called.

Sounds like a bug to me
(The current workaround is that I manage logic for the callback when it's called in the background)

**Comment by aaustin** [comment]
@arrows To confirm, waiting a little bit longer before you put it in the background the first time will correctly call init upon return?

**Comment by arrows** [comment]
Correct.
This only occurs if I go to the background very quick after launch.

**Comment by Alkalouti** [comment]
Hi All,

Any update for this issues.

+1

**Comment by ahmednawar** [comment]
@arrows @Alkalouti unfortunately this an extreme edge case that would require a substantial redesign of the SDK that we can't support. Sorry about that. I am closing here but feel free to reopen if you have any updates. Cheers!
