### ISSUE TITLE
BranchUniversalObject defines an enum inside of it's interface which is making it inaccessible in Swift 2.2

### ISSUE THREAD

**Issue by joshuafeldman** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#318]
It seems that Swift 2.2 does not play so nice with enumerations defined inside of an objective-c interface. It looks like it is making it private. `typedef NS_ENUM(NSInteger, ContentIndexMode)` should be moved outside of the `@interface BranchUniversalObject : NSObject`

**Comment by joshuafeldman** [comment]
Pull request https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/pull/319

**Comment by ahmednawar** [comment]
@joshuafeldman Nice find!

Thanks a lot for the PR. Appreciate it! will test it and push it with our next release

**Comment by ahmednawar** [comment]
@joshuafeldman the new SDK is out with your PR, thanks again!

closing here, if you have any issues please don't hesitate to open new issues..cheers!

**Comment by joshuafeldman** [comment]
@ahmednawar what release will this go in? I see your latest `0.12.0` does not have it.

**Comment by ahmednawar** [comment]
@joshuafeldman weird! I have merged your PR, you can see the commit message and the change here as well https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/blob/master/Branch-SDK/Branch-SDK/BranchUniversalObject.h#L21

How did you get the SDK? Pods, Carthage, Source?

**Comment by joshuafeldman** [comment]
@ahmednawar we are using the pod. You latest release is 11 commits behind master https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/releases/tag/0.12.0

**Comment by ahmednawar** [comment]
@joshuafeldman yeah there are usually commits for Carthage and there are some commits for CircleCI config. Unfortunately I merged your PR along with the Carthage ones which was after the release. My apologies! 

This means it will go in our next release. You could point to a specific commit (the merge one) in your Podfile as a temp workaround. Sorry about that.

**Comment by ahmednawar** [comment]
@joshuafeldman we've pushed a new release, can you update and let me know how it goes? Sorry for all the trouble.
