### ISSUE TITLE
Seeing a web view that says "Branch View Test" each time I launch my application after updating our pod to the latest

### ISSUE THREAD

**Issue by joshuafeldman** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#320]
I don't really understand what this is. It just started appearing after I updated our pod to the latest release. Some insight to what this is would be helpful and whether or not I should be seeing it.

![image](https://cloud.githubusercontent.com/assets/753652/13993299/02324490-f0dd-11e5-98bd-2132de1e217c.png)

**Comment by derrickstaten** [comment]
@joshuafeldman that's really embarrassing. We'll get this fixed right away. More to come.

**Comment by derrickstaten** [comment]
@joshuafeldman did you update yesterday between 4:30pm and 4:45pm PST?

Can you try clearing the Cocoapods cache and re-pulling the latest?

**Comment by derrickstaten** [comment]
@joshuafeldman we're unable to reproduce on our end. Can you send us your entry for Branch in the Podfile?

**Comment by joshuafeldman** [comment]
@derrickstaten I am actually using my fork which I synced to master yesterday until you guys bring in my pull request for Swift 2.2 

`pod 'Branch', :git => 'https://github.com/joshuafeldman/iOS-Deferred-Deep-Linking-SDK.git', :commit => 'a5274874ec114d8c984e2cc8e8b6d24b9d11b1d3'`

**Comment by joshuafeldman** [comment]
@derrickstaten it actually looks like my fork is now behind. Did you guys fix this yesterday?

**Comment by ahmednawar** [comment]
@joshuafeldman yeah there was a 15-minute window when the faulty code was live but we fixed it. Could you please update to latest master and see if this solves your issues? Sorry again for the headache

**Comment by joshuafeldman** [comment]
@derrickstaten @ahmednawar confirmed that it was just bad timing when I synced our fork to your master branch. I will go ahead and close this ticket and once https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/issues/318 is addressed I will switch back to your repository. Thanks guys for responding quickly as always 👊

**Comment by ahmednawar** [comment]
@joshuafeldman awesome! Always happy to help.
