### ISSUE TITLE
Promo code

### ISSUE THREAD

**Issue by imrihe** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#323]
validatePromo and applyPromo are not in the documentation of the SDK

**Comment by ahmednawar** [comment]
@imrihe We have inline documentation in `Branch.h` but nothing in our dev portal. They are deprecated methods as per our warning.

**Comment by ahmednawar** [comment]
@imrihe I am closing here. If you have any further questions, feel free to reopen.

Cheers!
