### ISSUE TITLE
Getting notified without polling

### ISSUE THREAD

**Issue by vondiplo** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#333]
How can I get notified when a referred friend has accepted the invitation and installed the app (credit is due) without polling the SDK ? Is there any notification mechanism?

**Comment by ahmednawar** [comment]
@vondiplo Sorry for the late response. The best way is to use a [webhook](https://dev.branch.io/getting-started/webhooks/guide/) which will send these events to your backend and you can decide what's the best way to use this data.

**Comment by ahmednawar** [comment]
@vondiplo I am closing here. If you have any questions, feel free to reopen. 

Cheers!
