### ISSUE TITLE
Calls to userCompletedAction containing \\ in an element of the withState-dictionary do not get through

### ISSUE THREAD

**Issue by everhardt** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#334]
Example:

```
Branch.getTestInstance().sharedInstance.userCompletedAction("error", withState: ["details":"\\"])
```

This call does not appear in the dashboard under Events, nor does it trigger the webhooks

**Comment by ahmednawar** [comment]
@everhardt Sorry for the late reply. Unfortunately you can't use these characters for events.

**Comment by everhardt** [comment]
Strange, I just found out that this is now fixed..

**Comment by everhardt** [comment]
That's pretty weird: the withState parameter can therefore never contain uncontrolled input. Which encoding should I apply to guarantee that a random string is valid?

**Comment by sojanpr** [comment]
@everhardt  Can you please use JSON Encoding for the strings you send with `userCompletedAction`. So in the above case `\\\\` instead of `\\` . Internally branch is converting the dictionary to Json and seems   like `\\` is invalid

**Comment by everhardt** [comment]
Okay, thanks!
