### ISSUE TITLE
 Clicking the Short URL generated by Branch.io  is not opening my iOS App

### ISSUE THREAD

**Issue by Govindakarthikeyan** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#339]
Hello,

I have integrated the Branch SDK through Cocoapods in my iOS App.

Branch.io settings:

Settings -> Link Settings -> I have checked these three options,
     1. Always try to open app
     2. I have an iOSApp -> Updated the values of "iOS URI Scheme" & "Custom URL"
     3. Enable Universal Links -> Updated the values of "Bundle Identifier" & "Apple App Prefix"

Finally, I got a short URL generated by Branch.io

iOS App configuration:
 1. Added a branch_key in Info.Plist
2. Added a URL scheme in the Info.plist as,
3. Enabled the Associated Domains in the Capabilities tab & added the "applinks:bnc.lt" as an entitlement
4. Also enabled the Associated Domains in the Apple Developer portal

I have followed those above steps for integrating the branch.io in my iOS App for the deep linking to work. I have tried deployed the App through Xcode & also tried deployed the App through Adhoc provisioning. But that short URL is not opening My iOS App

Please do the needful on this issue.

Thanks,
Govindakarthikeyan

**Comment by ahmednawar** [comment]
@Govindakarthikeyan could you please send us your branch key? If you prefer, you can also send it to support@branch.io and we'll take it from there.

**Comment by Govindakarthikeyan** [comment]
Hi ahmednawar,

Here is my branch key "key_live_iom1TfqjE2ONMpUY9EocahkcCtnckLq2"

**Comment by ahmednawar** [comment]
@Govindakarthikeyan I see that you sent a ticket to support with the same issue, let's continue the discussion there since there is more info.
